export const KEYS = {
  nav: {
    dashboard: "nav.items.dashboard",
    contentEngine: "nav.items.contentEngine",
    sumitSync: "nav.items.sumitSync",
    documents: "nav.items.documents",
    settings: "nav.items.settings",
  },
  dashboard: {
    title: "dashboard.title",
    subtitle: "dashboard.subtitle",
    cards: {
      activeDocuments: "dashboard.cards.activeDocuments",
      monthlySubmissions: "dashboard.cards.monthlySubmissions",
      pendingApproval: "dashboard.cards.pendingApproval",
      recentExports: "dashboard.cards.recentExports",
    },
    table: {
      title: "dashboard.table.title",
      col: {
        name: "dashboard.table.col.name",
        type: "dashboard.table.col.type",
        date: "dashboard.table.col.date",
        status: "dashboard.table.col.status",
        actions: "dashboard.table.col.actions",
      },
    },
  },
  common: {
    actions: {
      save: "common.actions.save",
      cancel: "common.actions.cancel",
      delete: "common.actions.delete",
      edit: "common.actions.edit",
      export: "common.actions.export",
      import: "common.actions.import",
      upload: "common.actions.upload",
      download: "common.actions.download",
      create: "common.actions.create",
      newDocument: "common.actions.newDocument",
      refresh: "common.actions.refresh",
      filter: "common.actions.filter",
      search: "common.actions.search",
      copy: "common.actions.copy",
      close: "common.actions.close",
      back: "common.actions.back",
      next: "common.actions.next",
      confirm: "common.actions.confirm",
      selectFile: "common.actions.selectFile",
      tryAgain: "common.actions.tryAgain",
    },
    messages: {
      saveSuccess: "common.messages.saveSuccess",
      deleteSuccess: "common.messages.deleteSuccess",
      exportSuccess: "common.messages.exportSuccess",
      uploadSuccess: "common.messages.uploadSuccess",
      copySuccess: "common.messages.copySuccess",
      genericSuccess: "common.messages.genericSuccess",
      saveError: "common.messages.saveError",
      loadError: "common.messages.loadError",
      networkError: "common.messages.networkError",
      timeoutError: "common.messages.timeoutError",
      permissionError: "common.messages.permissionError",
      notFound: "common.messages.notFound",
      invalidFormat: "common.messages.invalidFormat",
      fileTooLarge: "common.messages.fileTooLarge",
      sessionExpired: "common.messages.sessionExpired",
      genericError: "common.messages.genericError",
    },
    confirm: {
      deleteTitle: "common.confirm.deleteTitle",
      deleteBody: "common.confirm.deleteBody",
      deleteDocument: "common.confirm.deleteDocument",
      unsavedTitle: "common.confirm.unsavedTitle",
      unsavedBody: "common.confirm.unsavedBody",
      saveAndExit: "common.confirm.saveAndExit",
      exitWithout: "common.confirm.exitWithout",
    },
    emptyState: {
      title: "common.emptyState.title",
      subtitle: "common.emptyState.subtitle",
      documents: "common.emptyState.documents",
      activity: "common.emptyState.activity",
      results: "common.emptyState.results",
      searchResults: "common.emptyState.searchResults",
    },
  },
} as const;
