"""
Write plan data model for Summit API write-back.

A WritePlan is a list of WriteOperations generated by the sync engine.
Each operation describes what should be written to Summit (or skipped).
The plan can be reviewed before execution (dry-run mode).
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional
import json
import logging

logger = logging.getLogger(__name__)


class OpType(Enum):
    UPDATE_REPORT = "update_report"
    CREATE_REPORT = "create_report"
    UPDATE_CLIENT = "update_client"
    SKIP = "skip"
    FLAG = "flag"  # needs human attention


@dataclass
class WriteOperation:
    """Single write operation in the plan."""
    op_type: OpType
    entity_id: Optional[int]       # None for creates
    folder_id: str
    client_name: str
    match_key: str                 # ח.פ / ת"ז
    properties: Dict[str, Any]     # what to write
    old_values: Dict[str, Any]     # current values (for audit)
    reason: str
    client_entity_id: Optional[int] = None  # for creates — link to client

    def to_dict(self) -> Dict[str, Any]:
        return {
            "op_type": self.op_type.value,
            "entity_id": self.entity_id,
            "folder_id": self.folder_id,
            "client_name": self.client_name,
            "match_key": self.match_key,
            "properties": self.properties,
            "old_values": self.old_values,
            "reason": self.reason,
            "client_entity_id": self.client_entity_id,
        }


@dataclass
class WritePlan:
    """Collection of write operations with summary stats."""
    operations: List[WriteOperation] = field(default_factory=list)

    def add(self, op: WriteOperation):
        self.operations.append(op)

    @property
    def total(self) -> int:
        return len(self.operations)

    @property
    def updates(self) -> int:
        return sum(1 for o in self.operations if o.op_type == OpType.UPDATE_REPORT)

    @property
    def creates(self) -> int:
        return sum(1 for o in self.operations if o.op_type == OpType.CREATE_REPORT)

    @property
    def client_updates(self) -> int:
        return sum(1 for o in self.operations if o.op_type == OpType.UPDATE_CLIENT)

    @property
    def skips(self) -> int:
        return sum(1 for o in self.operations if o.op_type == OpType.SKIP)

    @property
    def flags(self) -> int:
        return sum(1 for o in self.operations if o.op_type == OpType.FLAG)

    def summary(self) -> Dict[str, int]:
        return {
            "total": self.total,
            "updates": self.updates,
            "creates": self.creates,
            "client_updates": self.client_updates,
            "skips": self.skips,
            "flags": self.flags,
        }

    def to_json(self) -> str:
        return json.dumps(
            {"summary": self.summary(), "operations": [o.to_dict() for o in self.operations]},
            ensure_ascii=False,
            indent=2,
        )


@dataclass
class WriteResult:
    """Result of executing a WritePlan."""
    dry_run: bool
    total_attempted: int = 0
    succeeded: int = 0
    failed: int = 0
    skipped: int = 0
    errors: List[Dict[str, str]] = field(default_factory=list)
    audit_log: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "dry_run": self.dry_run,
            "total_attempted": self.total_attempted,
            "succeeded": self.succeeded,
            "failed": self.failed,
            "skipped": self.skipped,
            "errors": self.errors,
            "audit_log": self.audit_log,
        }
